auto: true
markdown: rdiscount
pygments: true
permalink: /blog/:title
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/hyades.github.com/