# Mandatory settings

baseurl: /
name: Aayush Ahuja
paginate: 10
paginate_path: "/posts/page/:num/"
url: http://hyades.github.io
blog_theme: light # Or use dark

# Optional settings

discus_identifier: aayushahuja
ga_analytics: UA-41289176-1
rss_enabled: true # Change to false if not
social:
  dribbble: # Add your Dribbble link
  facebook: 
  github: https://github.com/hyades
  linkedin: http://in.linkedin.com/in/aayushahuja
  twitter: 
  email: aayushahuja@gmail.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

sass:
  sass_dir: assets/stylesheets
  sourcemap: never
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - bin/*
  - circle.yml
  - CLAUDE.md
  - files/resume/node_modules
  - files/resume/package-lock.json
  - files/resume/package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-archives
permalink: posts/:slug
