source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer"
gem "jekyll"
gem "jekyll-archives"
gem "jekyll-assets", "~> 2.4"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "mini_magick"
gem "sass"
gem "uglifier"

gem "kramdown-parser-gfm", "~> 1.1"
